// This file is automatically generated and contains assets from base.
// Generate for other networks by running: yarn generate-assets [network].

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA');
export const axlUSD_ADDRESS = Address.fromString('0xEB466342C4d449BC9f53A865D5Cb90586f405215');
export const DAI_ADDRESS = Address.fromString('0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA'), // USDC
    Address.fromString('0xEB466342C4d449BC9f53A865D5Cb90586f405215'), // axlUSD
    Address.fromString('0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb'), // DAI
  ],
  pricingAssets: [
    Address.fromString('0x4200000000000000000000000000000000000006'), // WETH
    Address.fromString('0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22'), // cbETH
    Address.fromString('0x27d2decb4bfc9c76f0309b8e88dec3a601fe25a8'), // BALD
    Address.fromString('0x6372Ec09dbf0c2907bB7B1529A1Fc6359310f1bd'), // SPT-stable
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
