// This file is automatically generated and contains assets from base.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x50c5725949A6F0c72E6C4a641F24049A917DB0Cb'), // USDC
  ],
  pricingAssets: [
    Address.fromString('0x4200000000000000000000000000000000000006'), // WETH
    Address.fromString('0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22'), // cbETH
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
