// This file is automatically generated and contains assets from base-goerli.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x3Ce827054de4536Fed802C0C466fAEe711AeA5ce');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x3Ce827054de4536Fed802C0C466fAEe711AeA5ce'), // USDC
  ],
  pricingAssets: [
    Address.fromString('0x4200000000000000000000000000000000000006'), // WETH
    Address.fromString('0x4fC531f8Ae7A7808E0dccCA08F1e3c7694582950'), // cbETH
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
